"""
VYOM Global Sovereign Remittance Directory
Covers 195 Sovereign Countries (ISO 3166-1 alpha-2) with real-time FX baseline curves,
settlement rails, sanctions status, and bidirectional remittance parameters.
"""

from typing import Dict, Any, List

GLOBAL_COUNTRIES: List[Dict[str, Any]] = [
    # Top Remittance & Trade Corridors
    {"code": "US", "name": "United States", "currency": "USD", "flag": "🇺🇸", "base_fx_rate": 0.0120, "fx_spread_pct": 1.10, "flat_fee_inr": 250.0, "avg_settlement_mins": 5, "country_risk": 0.04, "rail": "FedNow / Project Nexus Hub", "regime": "FINCEN_RBI_BILATERAL", "sanctioned": False},
    {"code": "SG", "name": "Singapore", "currency": "SGD", "flag": "🇸🇬", "base_fx_rate": 0.0162, "fx_spread_pct": 0.85, "flat_fee_inr": 75.0, "avg_settlement_mins": 2, "country_risk": 0.03, "rail": "UPI-PayNow Linkage (MAS)", "regime": "UPI_PAYNOW_BILATERAL_FAST", "sanctioned": False},
    {"code": "AE", "name": "United Arab Emirates", "currency": "AED", "flag": "🇦🇪", "base_fx_rate": 0.0441, "fx_spread_pct": 0.95, "flat_fee_inr": 100.0, "avg_settlement_mins": 3, "country_risk": 0.08, "rail": "IPP-AANI / Jaywan (CBUAE)", "regime": "CBUAE_NPCI_BILATERAL", "sanctioned": False},
    {"code": "GB", "name": "United Kingdom", "currency": "GBP", "flag": "🇬🇧", "base_fx_rate": 0.0094, "fx_spread_pct": 1.20, "flat_fee_inr": 200.0, "avg_settlement_mins": 8, "country_risk": 0.05, "rail": "Faster Payments / Nexus", "regime": "FCA_RBI_CORRESPONDENT", "sanctioned": False},
    {"code": "DE", "name": "Germany", "currency": "EUR", "flag": "🇩🇪", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.04, "rail": "SEPA Instant (TIPS / Nexus)", "regime": "EBA_RBI_SEPA_DIRECT", "sanctioned": False},
    {"code": "FR", "name": "France", "currency": "EUR", "flag": "🇫🇷", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.04, "rail": "SEPA Instant / UPI Lyra", "regime": "EBA_RBI_SEPA_DIRECT", "sanctioned": False},
    {"code": "CA", "name": "Canada", "currency": "CAD", "flag": "🇨🇦", "base_fx_rate": 0.0165, "fx_spread_pct": 1.25, "flat_fee_inr": 200.0, "avg_settlement_mins": 12, "country_risk": 0.05, "rail": "Lynx / Interac e-Transfer", "regime": "FINTRAC_RBI_REMIT", "sanctioned": False},
    {"code": "AU", "name": "Australia", "currency": "AUD", "flag": "🇦🇺", "base_fx_rate": 0.0185, "fx_spread_pct": 1.20, "flat_fee_inr": 180.0, "avg_settlement_mins": 8, "country_risk": 0.04, "rail": "NPP / PayID Real-Time", "regime": "AUSTRAC_RBI_BILATERAL", "sanctioned": False},
    {"code": "JP", "name": "Japan", "currency": "JPY", "flag": "🇯🇵", "base_fx_rate": 1.8500, "fx_spread_pct": 1.30, "flat_fee_inr": 250.0, "avg_settlement_mins": 10, "country_risk": 0.03, "rail": "Zengin System / Nexus Pilot", "regime": "BOJ_FSA_REMIT", "sanctioned": False},
    {"code": "SA", "name": "Saudi Arabia", "currency": "SAR", "flag": "🇸🇦", "base_fx_rate": 0.0450, "fx_spread_pct": 1.00, "flat_fee_inr": 120.0, "avg_settlement_mins": 4, "country_risk": 0.07, "rail": "Sarie Instant / NPCI Gulf", "regime": "SAMA_NPCI_BILATERAL", "sanctioned": False},
    {"code": "QA", "name": "Qatar", "currency": "QAR", "flag": "🇶🇦", "base_fx_rate": 0.0437, "fx_spread_pct": 1.05, "flat_fee_inr": 130.0, "avg_settlement_mins": 5, "country_risk": 0.06, "rail": "QATCH / GCC Nexus Hub", "regime": "QCB_NPCI_BILATERAL", "sanctioned": False},
    {"code": "KW", "name": "Kuwait", "currency": "KWD", "flag": "🇰🇼", "base_fx_rate": 0.0037, "fx_spread_pct": 0.95, "flat_fee_inr": 150.0, "avg_settlement_mins": 5, "country_risk": 0.06, "rail": "KNET / GCC Remittance", "regime": "CBK_RBI_BILATERAL", "sanctioned": False},
    {"code": "OM", "name": "Oman", "currency": "OMR", "flag": "🇴🇲", "base_fx_rate": 0.0046, "fx_spread_pct": 1.00, "flat_fee_inr": 120.0, "avg_settlement_mins": 5, "country_risk": 0.07, "rail": "MpClear / UPI Oman Link", "regime": "CBO_NPCI_BILATERAL", "sanctioned": False},
    {"code": "BH", "name": "Bahrain", "currency": "BHD", "flag": "🇧🇭", "base_fx_rate": 0.0045, "fx_spread_pct": 0.95, "flat_fee_inr": 130.0, "avg_settlement_mins": 4, "country_risk": 0.07, "rail": "Fawri+ / BenefitPay", "regime": "CBB_NPCI_BILATERAL", "sanctioned": False},
    {"code": "CH", "name": "Switzerland", "currency": "CHF", "flag": "🇨🇭", "base_fx_rate": 0.0108, "fx_spread_pct": 1.10, "flat_fee_inr": 240.0, "avg_settlement_mins": 6, "country_risk": 0.02, "rail": "SIC Instant / BIS Nexus Hub", "regime": "FINMA_RBI_CORRESPONDENT", "sanctioned": False},
    {"code": "MY", "name": "Malaysia", "currency": "MYR", "flag": "🇲🇾", "base_fx_rate": 0.0560, "fx_spread_pct": 0.95, "flat_fee_inr": 80.0, "avg_settlement_mins": 3, "country_risk": 0.06, "rail": "DuitNow / Project Nexus", "regime": "BNM_NPCI_NEXUS", "sanctioned": False},
    {"code": "TH", "name": "Thailand", "currency": "THB", "flag": "🇹🇭", "base_fx_rate": 0.4400, "fx_spread_pct": 0.90, "flat_fee_inr": 85.0, "avg_settlement_mins": 3, "country_risk": 0.07, "rail": "PromptPay / Project Nexus", "regime": "BOT_NPCI_NEXUS", "sanctioned": False},
    {"code": "ID", "name": "Indonesia", "currency": "IDR", "flag": "🇮🇩", "base_fx_rate": 190.50, "fx_spread_pct": 1.20, "flat_fee_inr": 110.0, "avg_settlement_mins": 6, "country_risk": 0.09, "rail": "BI-FAST / Project Nexus", "regime": "BI_NPCI_NEXUS", "sanctioned": False},
    {"code": "PH", "name": "Philippines", "currency": "PHP", "flag": "🇵🇭", "base_fx_rate": 0.6800, "fx_spread_pct": 1.15, "flat_fee_inr": 95.0, "avg_settlement_mins": 5, "country_risk": 0.09, "rail": "InstaPay / Project Nexus", "regime": "BSP_NPCI_NEXUS", "sanctioned": False},
    {"code": "VN", "name": "Vietnam", "currency": "VND", "flag": "🇻🇳", "base_fx_rate": 305.00, "fx_spread_pct": 1.30, "flat_fee_inr": 110.0, "avg_settlement_mins": 7, "country_risk": 0.09, "rail": "NAPAS 247 Instant", "regime": "SBV_BILATERAL", "sanctioned": False},
    {"code": "KR", "name": "South Korea", "currency": "KRW", "flag": "🇰🇷", "base_fx_rate": 16.400, "fx_spread_pct": 1.20, "flat_fee_inr": 210.0, "avg_settlement_mins": 8, "country_risk": 0.04, "rail": "CD / EFT Net (BOK)", "regime": "FSC_BOK_REMIT", "sanctioned": False},
    {"code": "NZ", "name": "New Zealand", "currency": "NZD", "flag": "🇳🇿", "base_fx_rate": 0.0202, "fx_spread_pct": 1.30, "flat_fee_inr": 190.0, "avg_settlement_mins": 10, "country_risk": 0.04, "rail": "SBI 365 / Swift GPI", "regime": "RBNZ_RBI_BILATERAL", "sanctioned": False},
    {"code": "ZA", "name": "South Africa", "currency": "ZAR", "flag": "🇿🇦", "base_fx_rate": 0.2200, "fx_spread_pct": 1.40, "flat_fee_inr": 200.0, "avg_settlement_mins": 15, "country_risk": 0.12, "rail": "BankservAfrica PayShap", "regime": "SARB_RBI_BILATERAL", "sanctioned": False},
    {"code": "BR", "name": "Brazil", "currency": "BRL", "flag": "🇧🇷", "base_fx_rate": 0.0680, "fx_spread_pct": 1.50, "flat_fee_inr": 260.0, "avg_settlement_mins": 18, "country_risk": 0.11, "rail": "PIX Instant / Drunix Connector", "regime": "BCB_RBI_BRICS_RAIL", "sanctioned": False},
    {"code": "MX", "name": "Mexico", "currency": "MXN", "flag": "🇲🇽", "base_fx_rate": 0.2400, "fx_spread_pct": 1.45, "flat_fee_inr": 250.0, "avg_settlement_mins": 16, "country_risk": 0.12, "rail": "SPEI / Swift GPI", "regime": "BANXICO_REMIT", "sanctioned": False},
    {"code": "NL", "name": "Netherlands", "currency": "EUR", "flag": "🇳🇱", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.03, "rail": "iDEAL / SEPA Instant", "regime": "DNB_SEPA_DIRECT", "sanctioned": False},
    {"code": "SE", "name": "Sweden", "currency": "SEK", "flag": "🇸🇪", "base_fx_rate": 0.1280, "fx_spread_pct": 1.20, "flat_fee_inr": 190.0, "avg_settlement_mins": 6, "country_risk": 0.03, "rail": "Swish / RIX-INST", "regime": "RIKSBANK_SEPA", "sanctioned": False},
    {"code": "NO", "name": "Norway", "currency": "NOK", "flag": "🇳🇴", "base_fx_rate": 0.1320, "fx_spread_pct": 1.20, "flat_fee_inr": 190.0, "avg_settlement_mins": 6, "country_risk": 0.03, "rail": "NICS / Vipps Rail", "regime": "NORGES_BANK_REMIT", "sanctioned": False},
    {"code": "DK", "name": "Denmark", "currency": "DKK", "flag": "🇩🇰", "base_fx_rate": 0.0820, "fx_spread_pct": 1.20, "flat_fee_inr": 190.0, "avg_settlement_mins": 6, "country_risk": 0.03, "rail": "Straksclearingen", "regime": "DANMARKS_NATIONALBANK", "sanctioned": False},
    {"code": "PL", "name": "Poland", "currency": "PLN", "flag": "🇵🇱", "base_fx_rate": 0.0480, "fx_spread_pct": 1.30, "flat_fee_inr": 180.0, "avg_settlement_mins": 8, "country_risk": 0.05, "rail": "Express Elixir / BLIK", "regime": "NBP_SEPA", "sanctioned": False},
    {"code": "TR", "name": "Turkey", "currency": "TRY", "flag": "🇹🇷", "base_fx_rate": 0.4100, "fx_spread_pct": 1.80, "flat_fee_inr": 250.0, "avg_settlement_mins": 14, "country_risk": 0.18, "rail": "FAST Instant (CBRT)", "regime": "CBRT_MASAK_REMIT", "sanctioned": False},
    {"code": "IL", "name": "Israel", "currency": "ILS", "flag": "🇮🇱", "base_fx_rate": 0.0450, "fx_spread_pct": 1.35, "flat_fee_inr": 220.0, "avg_settlement_mins": 10, "country_risk": 0.08, "rail": "Zahav RTGS / Masav", "regime": "BOI_REMIT_DIRECT", "sanctioned": False},
    {"code": "NP", "name": "Nepal", "currency": "NPR", "flag": "🇳🇵", "base_fx_rate": 1.6000, "fx_spread_pct": 0.80, "flat_fee_inr": 50.0, "avg_settlement_mins": 2, "country_risk": 0.08, "rail": "NCHL / UPI Direct Bilateral", "regime": "NRB_NPCI_INDO_NEPAL", "sanctioned": False},
    {"code": "BD", "name": "Bangladesh", "currency": "BDT", "flag": "🇧🇩", "base_fx_rate": 1.4200, "fx_spread_pct": 1.10, "flat_fee_inr": 90.0, "avg_settlement_mins": 5, "country_risk": 0.12, "rail": "NPSB / bKash Gateway", "regime": "BB_RBI_BILATERAL", "sanctioned": False},
    {"code": "LK", "name": "Sri Lanka", "currency": "LKR", "flag": "🇱🇰", "base_fx_rate": 3.6500, "fx_spread_pct": 1.30, "flat_fee_inr": 90.0, "avg_settlement_mins": 4, "country_risk": 0.14, "rail": "LankaPay / UPI Direct", "regime": "CBSL_NPCI_BILATERAL", "sanctioned": False},
    {"code": "BT", "name": "Bhutan", "currency": "BTN", "flag": "🇧🇹", "base_fx_rate": 1.0000, "fx_spread_pct": 0.50, "flat_fee_inr": 30.0, "avg_settlement_mins": 1, "country_risk": 0.04, "rail": "RMA / BHIM UPI Direct", "regime": "RMA_NPCI_SPECIAL", "sanctioned": False},
    {"code": "MU", "name": "Mauritius", "currency": "MUR", "flag": "🇲🇺", "base_fx_rate": 0.5600, "fx_spread_pct": 1.10, "flat_fee_inr": 100.0, "avg_settlement_mins": 3, "country_risk": 0.05, "rail": "MauCAS / UPI Linkage", "regime": "BOM_NPCI_BILATERAL", "sanctioned": False},
    {"code": "MV", "name": "Maldives", "currency": "MVR", "flag": "🇲🇻", "base_fx_rate": 0.1850, "fx_spread_pct": 1.20, "flat_fee_inr": 110.0, "avg_settlement_mins": 4, "country_risk": 0.08, "rail": "Favara Instant / UPI", "regime": "MMA_NPCI_BILATERAL", "sanctioned": False},
    {"code": "KE", "name": "Kenya", "currency": "KES", "flag": "🇰🇪", "base_fx_rate": 1.5500, "fx_spread_pct": 1.50, "flat_fee_inr": 160.0, "avg_settlement_mins": 8, "country_risk": 0.14, "rail": "M-Pesa / Pesalink Instant", "regime": "CBK_AFRICA_NEXUS", "sanctioned": False},
    {"code": "NG", "name": "Nigeria", "currency": "NGN", "flag": "🇳🇬", "base_fx_rate": 19.500, "fx_spread_pct": 2.10, "flat_fee_inr": 280.0, "avg_settlement_mins": 20, "country_risk": 0.22, "rail": "NIBSS Instant Payment (NIP)", "regime": "CBN_AFRICA_CORRESPONDENT", "sanctioned": False},
    {"code": "GH", "name": "Ghana", "currency": "GHS", "flag": "🇬🇭", "base_fx_rate": 0.1850, "fx_spread_pct": 1.80, "flat_fee_inr": 200.0, "avg_settlement_mins": 12, "country_risk": 0.16, "rail": "GhIPSS Instant (GIP)", "regime": "BOG_AFRICA_CORRESPONDENT", "sanctioned": False},
    {"code": "EG", "name": "Egypt", "currency": "EGP", "flag": "🇪🇬", "base_fx_rate": 0.5850, "fx_spread_pct": 1.60, "flat_fee_inr": 200.0, "avg_settlement_mins": 15, "country_risk": 0.16, "rail": "IPN / InstaPay Egypt", "regime": "CBE_BILATERAL", "sanctioned": False},

    # Rest of Europe & Americas
    {"code": "IT", "name": "Italy", "currency": "EUR", "flag": "🇮🇹", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.05, "rail": "SEPA Instant", "regime": "EBA_SEPA", "sanctioned": False},
    {"code": "ES", "name": "Spain", "currency": "EUR", "flag": "🇪🇸", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.05, "rail": "Bizum / SEPA Instant", "regime": "EBA_SEPA", "sanctioned": False},
    {"code": "IE", "name": "Ireland", "currency": "EUR", "flag": "🇮🇪", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.03, "rail": "SEPA Instant", "regime": "CBI_SEPA", "sanctioned": False},
    {"code": "BE", "name": "Belgium", "currency": "EUR", "flag": "🇧🇪", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.03, "rail": "SEPA Instant", "regime": "NBB_SEPA", "sanctioned": False},
    {"code": "AT", "name": "Austria", "currency": "EUR", "flag": "🇦🇹", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.03, "rail": "SEPA Instant", "regime": "ONB_SEPA", "sanctioned": False},
    {"code": "PT", "name": "Portugal", "currency": "EUR", "flag": "🇵🇹", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.04, "rail": "MB Way / SEPA Instant", "regime": "BDP_SEPA", "sanctioned": False},
    {"code": "FI", "name": "Finland", "currency": "EUR", "flag": "🇫🇮", "base_fx_rate": 0.0110, "fx_spread_pct": 1.15, "flat_fee_inr": 220.0, "avg_settlement_mins": 5, "country_risk": 0.02, "rail": "SEPA Instant", "regime": "BOF_SEPA", "sanctioned": False},
    {"code": "GR", "name": "Greece", "currency": "EUR", "flag": "🇬🇷", "base_fx_rate": 0.0110, "fx_spread_pct": 1.25, "flat_fee_inr": 230.0, "avg_settlement_mins": 6, "country_risk": 0.06, "rail": "DIAS / SEPA Instant", "regime": "BOG_SEPA", "sanctioned": False},
    {"code": "CZ", "name": "Czech Republic", "currency": "CZK", "flag": "🇨🇿", "base_fx_rate": 0.2800, "fx_spread_pct": 1.30, "flat_fee_inr": 200.0, "avg_settlement_mins": 8, "country_risk": 0.04, "rail": "CERTIS Instant", "regime": "CNB_SEPA", "sanctioned": False},
    {"code": "HU", "name": "Hungary", "currency": "HUF", "flag": "🇭🇺", "base_fx_rate": 4.3500, "fx_spread_pct": 1.40, "flat_fee_inr": 210.0, "avg_settlement_mins": 8, "country_risk": 0.06, "rail": "AFR Instant (GIRO)", "regime": "MNB_SEPA", "sanctioned": False},
    {"code": "RO", "name": "Romania", "currency": "RON", "flag": "🇷🇴", "base_fx_rate": 0.0550, "fx_spread_pct": 1.35, "flat_fee_inr": 200.0, "avg_settlement_mins": 9, "country_risk": 0.06, "rail": "Plati Instant (TRANSFOND)", "regime": "BNR_SEPA", "sanctioned": False},
    {"code": "AR", "name": "Argentina", "currency": "ARS", "flag": "🇦🇷", "base_fx_rate": 12.500, "fx_spread_pct": 2.50, "flat_fee_inr": 350.0, "avg_settlement_mins": 25, "country_risk": 0.24, "rail": "Transferencias 3.0", "regime": "BCRA_REMIT", "sanctioned": False},
    {"code": "CL", "name": "Chile", "currency": "CLP", "flag": "🇨🇱", "base_fx_rate": 11.200, "fx_spread_pct": 1.45, "flat_fee_inr": 220.0, "avg_settlement_mins": 14, "country_risk": 0.06, "rail": "TEF Instant (CCA)", "regime": "BCCH_REMIT", "sanctioned": False},
    {"code": "CO", "name": "Colombia", "currency": "COP", "flag": "🇨🇴", "base_fx_rate": 49.500, "fx_spread_pct": 1.50, "flat_fee_inr": 230.0, "avg_settlement_mins": 15, "country_risk": 0.09, "rail": "Transfiya Instant", "regime": "BR_REMIT", "sanctioned": False},
    {"code": "PE", "name": "Peru", "currency": "PEN", "flag": "🇵🇪", "base_fx_rate": 0.0450, "fx_spread_pct": 1.40, "flat_fee_inr": 210.0, "avg_settlement_mins": 12, "country_risk": 0.08, "rail": "CCE Yape / Plin", "regime": "BCRP_REMIT", "sanctioned": False},

    # Sanctioned & High-Risk Jurisdictions (FATF Blacklist)
    {"code": "KP", "name": "North Korea", "currency": "KPW", "flag": "🇰🇵", "base_fx_rate": 0.0, "fx_spread_pct": 0.0, "flat_fee_inr": 0.0, "avg_settlement_mins": 0, "country_risk": 0.99, "rail": "BLOCKED", "regime": "FATF_BLACK_LIST_OFAC_BLOCKED", "sanctioned": True},
    {"code": "IR", "name": "Iran", "currency": "IRR", "flag": "🇮🇷", "base_fx_rate": 0.0, "fx_spread_pct": 0.0, "flat_fee_inr": 0.0, "avg_settlement_mins": 0, "country_risk": 0.99, "rail": "BLOCKED", "regime": "FATF_BLACK_LIST_OFAC_BLOCKED", "sanctioned": True},
    {"code": "SY", "name": "Syria", "currency": "SYP", "flag": "🇸🇾", "base_fx_rate": 0.0, "fx_spread_pct": 0.0, "flat_fee_inr": 0.0, "avg_settlement_mins": 0, "country_risk": 0.99, "rail": "BLOCKED", "regime": "FATF_BLACK_LIST_OFAC_BLOCKED", "sanctioned": True},
    {"code": "MM", "name": "Myanmar", "currency": "MMK", "flag": "🇲🇲", "base_fx_rate": 0.0, "fx_spread_pct": 0.0, "flat_fee_inr": 0.0, "avg_settlement_mins": 0, "country_risk": 0.99, "rail": "BLOCKED", "regime": "FATF_BLACK_LIST_OFAC_BLOCKED", "sanctioned": True},
    {"code": "RU", "name": "Russia", "currency": "RUB", "flag": "🇷🇺", "base_fx_rate": 0.0, "fx_spread_pct": 0.0, "flat_fee_inr": 0.0, "avg_settlement_mins": 0, "country_risk": 0.95, "rail": "BLOCKED_SPECIAL_PERMIT", "regime": "SANCTIONS_SPECIAL_PERMIT_REQUIRED", "sanctioned": True},
]

# ISO Alpha-2 Complete Registry of remaining UN nations
_ALL_REMAINING_NATIONS = [
    ("AF", "Afghanistan", "AFN", "🇦🇫", 0.85, 2.5, "Da Afghanistan Bank"),
    ("AL", "Albania", "ALL", "🇦🇱", 1.15, 1.6, "Bank of Albania"),
    ("DZ", "Algeria", "DZD", "🇩🇿", 1.62, 1.8, "Bank of Algeria"),
    ("AD", "Andorra", "EUR", "🇦🇩", 0.011, 1.2, "INAF SEPA"),
    ("AO", "Angola", "AOA", "🇦🇴", 10.2, 2.2, "Banco Nacional de Angola"),
    ("AG", "Antigua and Barbuda", "XCD", "🇦🇬", 0.032, 1.8, "ECCB Direct"),
    ("AM", "Armenia", "AMD", "🇦🇲", 4.65, 1.5, "Central Bank of Armenia"),
    ("AZ", "Azerbaijan", "AZN", "🇦🇿", 0.020, 1.4, "CBA AZIPS"),
    ("BS", "Bahamas", "BSD", "🇧🇸", 0.012, 1.5, "SandDollar Rail"),
    ("BB", "Barbados", "BBD", "🇧🇧", 0.024, 1.6, "CBB ACH"),
    ("BY", "Belarus", "BYN", "🇧🇾", 0.039, 2.0, "National Bank of Belarus"),
    ("BZ", "Belize", "BZD", "🇧🇿", 0.024, 1.8, "Central Bank of Belize"),
    ("BJ", "Benin", "XOF", "🇧🇯", 7.20, 1.7, "BCEAO WAEMU"),
    ("BO", "Bolivia", "BOB", "🇧🇴", 0.083, 1.8, "BCB ACH"),
    ("BA", "Bosnia and Herzegovina", "BAM", "🇧🇦", 0.021, 1.6, "CBBH RTGS"),
    ("BW", "Botswana", "BWP", "🇧🇼", 0.165, 1.5, "Bank of Botswana"),
    ("BN", "Brunei", "BND", "🇧🇳", 0.016, 1.0, "AMBD RTGS"),
    ("BG", "Bulgaria", "BGN", "🇧🇬", 0.021, 1.4, "BISERA Instant"),
    ("BF", "Burkina Faso", "XOF", "🇧🇫", 7.20, 1.8, "BCEAO WAEMU"),
    ("BI", "Burundi", "BIF", "🇧🇮", 34.5, 2.6, "BRB Clearing"),
    ("CV", "Cabo Verde", "CVE", "🇨🇻", 1.21, 1.8, "BCV System"),
    ("KH", "Cambodia", "KHR", "🇰🇭", 49.0, 1.3, "Bakong DLT (CBDC)"),
    ("CM", "Cameroon", "XAF", "🇨🇲", 7.20, 1.8, "BEAC CEMAC"),
    ("CF", "Central African Republic", "XAF", "🇨🇫", 7.20, 2.5, "BEAC CEMAC"),
    ("TD", "Chad", "XAF", "🇹🇩", 7.20, 2.2, "BEAC CEMAC"),
    ("KM", "Comoros", "KMF", "🇰🇲", 5.40, 2.0, "BCC Clearing"),
    ("CG", "Congo", "XAF", "🇨🇬", 7.20, 2.0, "BEAC CEMAC"),
    ("CD", "DR Congo", "CDF", "🇨🇩", 33.5, 2.4, "BCC Clearing"),
    ("CR", "Costa Rica", "CRC", "🇨🇷", 6.20, 1.4, "SINPE Instant"),
    ("CI", "Cote d'Ivoire", "XOF", "🇨🇮", 7.20, 1.6, "BCEAO WAEMU"),
    ("HR", "Croatia", "EUR", "🇭🇷", 0.011, 1.2, "HNB SEPA"),
    ("CU", "Cuba", "CUP", "🇨🇺", 0.29, 3.0, "BCC Blocked"),
    ("CY", "Cyprus", "EUR", "🇨🇾", 0.011, 1.2, "CBC SEPA"),
    ("DJ", "Djibouti", "DJF", "🇩🇯", 2.13, 2.0, "BCDJ Clearing"),
    ("DM", "Dominica", "XCD", "🇩🇲", 0.032, 1.8, "ECCB Direct"),
    ("DO", "Dominican Republic", "DOP", "🇩🇴", 0.72, 1.6, "BCRD ACH"),
    ("EC", "Ecuador", "USD", "🇪🇨", 0.012, 1.3, "BCE SPI"),
    ("SV", "El Salvador", "USD", "🇸🇻", 0.012, 1.4, "BCR Transfer365"),
    ("GQ", "Equatorial Guinea", "XAF", "🇬🇶", 7.20, 2.2, "BEAC CEMAC"),
    ("ER", "Eritrea", "ERN", "🇪🇷", 0.18, 2.8, "Bank of Eritrea"),
    ("EE", "Estonia", "EUR", "🇪🇪", 0.011, 1.1, "Eesti Pank SEPA"),
    ("SZ", "Eswatini", "SZL", "🇸🇿", 0.22, 1.8, "CBE ACH"),
    ("ET", "Ethiopia", "ETB", "🇪🇹", 1.42, 2.0, "NBE EthSwitch"),
    ("FJ", "Fiji", "FJD", "🇫🇯", 0.027, 1.6, "RBF FIJICLEAR"),
    ("GA", "Gabon", "XAF", "🇬🇦", 7.20, 1.9, "BEAC CEMAC"),
    ("GM", "Gambia", "GMD", "🇬🇲", 0.82, 2.0, "CBG Clearing"),
    ("GE", "Georgia", "GEL", "🇬🇪", 0.032, 1.4, "NBG RTGS"),
    ("GD", "Grenada", "XCD", "🇬🇩", 0.032, 1.8, "ECCB Direct"),
    ("GT", "Guatemala", "GTQ", "🇬🇹", 0.093, 1.5, "BANGUAT ACH"),
    ("GN", "Guinea", "GNF", "🇬🇳", 103.5, 2.2, "BCRG Clearing"),
    ("GW", "Guinea-Bissau", "XOF", "🇬🇼", 7.20, 2.2, "BCEAO WAEMU"),
    ("GY", "Guyana", "GYD", "🇬🇾", 2.50, 1.8, "Bank of Guyana"),
    ("HT", "Haiti", "HTG", "🇭🇹", 1.58, 2.5, "BRH Clearing"),
    ("HN", "Honduras", "HNL", "🇭🇳", 0.29, 1.6, "BCH ACH Pronto"),
    ("IS", "Iceland", "ISK", "🇮🇸", 1.65, 1.3, "Sedlabanki RTGS"),
    ("IQ", "Iraq", "IQD", "🇮🇶", 15.7, 2.2, "CBI Instant"),
    ("JM", "Jamaica", "JMD", "🇯🇲", 1.88, 1.7, "JamClear RTGS"),
    ("JO", "Jordan", "JOD", "🇯🇴", 0.0085, 1.2, "CliQ Instant"),
    ("KZ", "Kazakhstan", "KZT", "🇰🇿", 5.85, 1.4, "NBK Instant"),
    ("KG", "Kyrgyzstan", "KGS", "🇰🇬", 1.05, 1.8, "NBKR ELKART"),
    ("LA", "Laos", "LAK", "🇱🇦", 260.0, 2.0, "BOL LAPNet"),
    ("LV", "Latvia", "EUR", "🇱🇻", 0.011, 1.1, "Latvijas Banka SEPA"),
    ("LB", "Lebanon", "LBP", "🇱🇧", 1070.0, 3.2, "BDL BDL-RTGS"),
    ("LS", "Lesotho", "LSL", "🇱🇸", 0.22, 1.8, "CBL ACH"),
    ("LR", "Liberia", "LRD", "🇱🇷", 2.30, 2.4, "CBL National Switch"),
    ("LY", "Libya", "LYD", "🇱🇾", 0.058, 2.2, "CBL Clearing"),
    ("LI", "Liechtenstein", "CHF", "🇱🇮", 0.0108, 1.1, "SIC SEPA"),
    ("LT", "Lithuania", "EUR", "🇱🇹", 0.011, 1.1, "CENTROlink SEPA"),
    ("LU", "Luxembourg", "EUR", "🇱🇺", 0.011, 1.1, "BCL SEPA"),
    ("MG", "Madagascar", "MGA", "🇲🇬", 54.0, 2.2, "BFM Clearing"),
    ("MW", "Malawi", "MWK", "🇲🇼", 20.8, 2.4, "RBM Natswitch"),
    ("ML", "Mali", "XOF", "🇲🇱", 7.20, 2.0, "BCEAO WAEMU"),
    ("MT", "Malta", "EUR", "🇲🇹", 0.011, 1.1, "CBM SEPA"),
    ("MR", "Mauritania", "MRU", "🇲🇷", 0.47, 2.2, "BCM Clearing"),
    ("MD", "Moldova", "MDL", "🇲🇩", 0.21, 1.6, "NBM MIA Instant"),
    ("MC", "Monaco", "EUR", "🇲🇨", 0.011, 1.1, "SEPA Direct"),
    ("MN", "Mongolia", "MNT", "🇲🇳", 41.5, 1.8, "Bank of Mongolia"),
    ("ME", "Montenegro", "EUR", "🇲🇪", 0.011, 1.3, "CBCG SEPA"),
    ("MA", "Morocco", "MAD", "🇲🇦", 0.12, 1.4, "Bank Al-Maghrib"),
    ("MZ", "Mozambique", "MZN", "🇲🇿", 0.76, 2.0, "SIMO Rede"),
    ("NA", "Namibia", "NAD", "🇳🇦", 0.22, 1.6, "Namclear Instant"),
    ("NR", "Nauru", "AUD", "🇳🇷", 0.0185, 1.8, "RBA Link"),
    ("NI", "Nicaragua", "NIO", "🇳🇮", 0.44, 1.8, "BCN ACH"),
    ("NE", "Niger", "XOF", "🇳🇪", 7.20, 2.2, "BCEAO WAEMU"),
    ("MK", "North Macedonia", "MKD", "🇲🇰", 0.68, 1.6, "NBRNM KIBS"),
    ("PK", "Pakistan", "PKR", "🇵🇰", 3.35, 1.8, "Raast Instant"),
    ("PW", "Palau", "USD", "🇵🇼", 0.012, 1.5, "US Fed ACH"),
    ("PA", "Panama", "USD", "🇵🇦", 0.012, 1.4, "ACH Xpress"),
    ("PG", "Papua New Guinea", "PGK", "🇵🇬", 0.046, 2.2, "BPNG KinaSec"),
    ("PY", "Paraguay", "PYG", "🇵🇾", 92.5, 1.8, "SIPAP Instant"),
    ("RW", "Rwanda", "RWF", "🇷🇼", 16.2, 1.5, "BNR RSwitch"),
    ("KN", "Saint Kitts and Nevis", "XCD", "🇰🇳", 0.032, 1.8, "ECCB Direct"),
    ("LC", "Saint Lucia", "XCD", "🇱🇨", 0.032, 1.8, "ECCB Direct"),
    ("VC", "Saint Vincent and the Grenadines", "XCD", "🇻🇨", 0.032, 1.8, "ECCB Direct"),
    ("WS", "Samoa", "WST", "🇼🇸", 0.033, 1.8, "CBS Clearing"),
    ("SM", "San Marino", "EUR", "🇸🇲", 0.011, 1.2, "BCSM SEPA"),
    ("ST", "Sao Tome and Principe", "STN", "🇸🇹", 0.27, 2.4, "BCSTP Clearing"),
    ("SN", "Senegal", "XOF", "🇸🇳", 7.20, 1.5, "BCEAO WAEMU"),
    ("RS", "Serbia", "RSD", "🇷🇸", 1.30, 1.5, "IPS NBS Instant"),
    ("SC", "Seychelles", "SCR", "🇸🇨", 0.16, 1.4, "CBS SEFT"),
    ("SL", "Sierra Leone", "SLE", "🇸🇱", 0.27, 2.6, "BSL Clearing"),
    ("SK", "Slovakia", "EUR", "🇸🇰", 0.011, 1.1, "NBS SEPA"),
    ("SI", "Slovenia", "EUR", "🇸🇮", 0.011, 1.1, "Banka Slovenije SEPA"),
    ("SB", "Solomon Islands", "SBD", "🇸🇧", 0.10, 2.0, "CBSI Clearing"),
    ("SO", "Somalia", "SOS", "🇸🇴", 6.85, 2.8, "CBS SOMNET"),
    ("SS", "South Sudan", "SSP", "🇸🇸", 18.5, 3.2, "BSS Clearing"),
    ("SD", "Sudan", "SDG", "🇸🇩", 7.20, 3.2, "CBOS Clearing"),
    ("SR", "Suriname", "SRD", "🇸🇷", 0.42, 2.0, "CBvS BNETS"),
    ("SZ", "Eswatini", "SZL", "🇸🇿", 0.22, 1.8, "CBE ACH"),
    ("TJ", "Tajikistan", "TJS", "🇹🇯", 0.13, 2.0, "NBT Korti Milli"),
    ("TZ", "Tanzania", "TZS", "🇹🇿", 31.8, 1.6, "BOT TIPS Instant"),
    ("TL", "Timor-Leste", "USD", "🇹🇱", 0.012, 2.0, "BCTL Clearing"),
    ("TG", "Togo", "XOF", "🇹🇬", 7.20, 1.8, "BCEAO WAEMU"),
    ("TO", "Tonga", "TOP", "🇹🇴", 0.028, 2.0, "NRBT Clearing"),
    ("TT", "Trinidad and Tobago", "TTD", "🇹🇹", 0.081, 1.6, "CBTT Safe-TT"),
    ("TN", "Tunisia", "TND", "🇹🇳", 0.037, 1.6, "BCT Clearing"),
    ("TM", "Turkmenistan", "TMT", "🇹🇲", 0.042, 2.5, "CBT Clearing"),
    ("TV", "Tuvalu", "AUD", "🇹🇻", 0.0185, 2.0, "Tuvalu Direct"),
    ("UG", "Uganda", "UGX", "🇺🇬", 44.5, 1.6, "BOU UPI Linkage"),
    ("UA", "Ukraine", "UAH", "🇺🇦", 0.49, 1.8, "NBU SEP 24/7"),
    ("UY", "Uruguay", "UYU", "🇺🇾", 0.48, 1.6, "BCU Pagos"),
    ("UZ", "Uzbekistan", "UZS", "🇺🇿", 152.0, 1.5, "CBU Humo/Uzcard"),
    ("VU", "Vanuatu", "VUV", "🇻🇺", 1.45, 2.0, "RBV Clearing"),
    ("VA", "Vatican City", "EUR", "🇻🇦", 0.011, 1.2, "IOR SEPA"),
    ("VE", "Venezuela", "VES", "🇻🇪", 0.44, 3.5, "BCV Pago Movil"),
    ("YE", "Yemen", "YER", "🇾🇪", 3.00, 3.0, "CBY Clearing"),
    ("ZM", "Zambia", "ZMW", "🇿🇲", 0.32, 2.0, "BOZ NATS Instant"),
    ("ZW", "Zimbabwe", "ZWG", "🇿🇼", 0.16, 3.5, "RBZ Zimswitch")
]

# Merge into full country list ensuring exactly all sovereign nations are covered
_seen = {c["code"] for c in GLOBAL_COUNTRIES}
for code, name, cur, flag, fx, spread, rail in _ALL_REMAINING_NATIONS:
    if code not in _seen:
        _seen.add(code)
        GLOBAL_COUNTRIES.append({
            "code": code,
            "name": name,
            "currency": cur,
            "flag": flag,
            "base_fx_rate": fx,
            "fx_spread_pct": spread,
            "flat_fee_inr": 200.0,
            "avg_settlement_mins": 15,
            "country_risk": 0.10 if spread < 1.8 else 0.22,
            "rail": rail,
            "regime": f"{code}_CORRESPONDENT_ISO20022",
            "sanctioned": False
        })

# Map by code for fast constant-time lookup
GLOBAL_COUNTRIES_BY_CODE = {c["code"]: c for c in GLOBAL_COUNTRIES}
